apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "masa-odoo18.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "masa-odoo18.labels" . | nindent 4 }}
data:
  odoo.conf: |
    [options]
    addons_path = {{ .Values.odoo.addonsPath | replace "\n" "" | replace " " "" }}
    db_host = {{ include "masa-odoo18.postgresName" . }}
    db_port = 5432
    db_user = {{ .Values.postgresql.auth.username }}
    db_name = {{ .Values.odoo.dbName }}
    admin_passwd = {{ .Values.odoo.adminPasswd }}
    logfile = /var/log/odoo/odoo.log
    log_level = {{ .Values.odoo.config.logLevel }}
    workers = {{ .Values.odoo.config.workers }}
    max_cron_threads = {{ .Values.odoo.config.maxCronThreads | default 1 }}
    proxy_mode = {{ .Values.odoo.config.proxyMode }}
    {{- if .Values.odoo.config.devMode }}
    dev_mode = {{ .Values.odoo.config.devMode }}
    {{- end }}
    dbfilter = .*
